development:
  sessions:
    default:
      database: enterprise_position_level_dev
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: enterprise_position_level_test
      hosts:
        - localhost:27017
